#include <cstdlib>
#include <iostream>
#include <memory>

#include <ure/native_scene_ir.hpp>
#include <ure/native_simulation_contract.hpp>

namespace {
int failures = 0;
void check(bool condition, const char* message) { if (!condition) { std::cerr << "FAIL: " << message << '\n'; ++failures; } }
ure::native_scene::SimulationCapabilityRegistry capabilities() { using namespace ure::native_scene; SimulationCapabilityRegistry result; result.solvers.emplace("ure.physics.current", Version{1, 2}); result.solvers.emplace("ure.acoustic.modal", Version{1, 0}); result.domains = {SimulationDomain::RigidBody, SimulationDomain::Fluid, SimulationDomain::AcousticModal}; result.coupling_semantics = {CouplingSemantic::Transform, CouplingSemantic::CollisionImpulse, CouplingSemantic::AudioSignal}; return result; }
ure::native_scene::NativeSimulationContract contract() { using namespace ure::native_scene; NativeSimulationContract value; value.id = "simulation/full"; value.schema_version = {1, 0}; value.time = {0, 120, 60, 1, 0}; value.domains.push_back({"physics", SimulationDomain::RigidBody, RequirementLevel::Required, "ure.physics.current", {1, 1}, {"physics/state", "coupling/impact"}, {}}); value.domains.push_back({"fluid", SimulationDomain::Fluid, RequirementLevel::Required, "ure.physics.current", {1, 2}, {"fluid/particles"}, {}}); value.domains.push_back({"acoustic", SimulationDomain::AcousticModal, RequirementLevel::Required, "ure.acoustic.modal", {1, 0}, {"acoustic/modes"}, {}}); value.coupling.push_back({"impact", "physics", "acoustic", CouplingSemantic::CollisionImpulse, RequirementLevel::Required, 60, 1, 0, false, "coupling/impact", {}}); value.migrations.push_back({"physics", {1, 0}, {1, 1}, "ure-migrate-physics", false}); return value; }
}
int main() { using namespace ure::native_scene; auto registry = capabilities(); auto value = contract(); const auto compiled = compile_simulation_contract(value, registry); check(compiled.ok() && compiled.physics->enabled && compiled.physics->fluid.enabled, "supported physics subset did not compile"); check(compiled.physics && compiled.physics->total_frames == 121, "time sampling did not map"); const auto binary = write_simulation_contract_binary(value); const auto loaded = read_simulation_contract_binary(binary); check(loaded.ok() && simulation_contract_semantic_hash(*loaded.value) == simulation_contract_semantic_hash(value), "URPC binary roundtrip failed"); const auto text = write_simulation_contract_text(value); const auto text_loaded = read_simulation_contract_text(text); check(text_loaded.ok() && simulation_contract_semantic_hash(*text_loaded.value) == simulation_contract_semantic_hash(value), "URPC text roundtrip failed"); auto unsupported = value; unsupported.domains[2].solver_id = "future.acoustic"; check(!compile_simulation_contract(unsupported, registry).ok(), "unknown required solver accepted"); unsupported.domains[2].requirement = RequirementLevel::Optional; check(compile_simulation_contract(unsupported, registry).ok(), "unknown optional solver was not retained"); auto cycle = value; cycle.coupling.push_back({"feedback", "acoustic", "physics", CouplingSemantic::AudioSignal, RequirementLevel::Required, 60, 1, 0, false, {}, {}}); check(!validate_simulation_contract(cycle, registry).ok(), "coupling cycle without feedback accepted"); cycle.coupling[0].feedback = true; cycle.coupling[1].feedback = true; check(validate_simulation_contract(cycle, registry).ok(), "explicit feedback cycle rejected"); ure::scene_ir::SceneIR scene; SceneDocument document; document.id = "scene/q8"; document.schema_version = {1, 0}; document.features.push_back({"ure.scene.simulation", {1, 0}, RequirementLevel::Required, "ure", {}, "{}"}); auto archive = make_native_scene_archive(std::move(document), scene); archive.simulation_contract = std::make_shared<const NativeSimulationContract>(value); CapabilityRegistry native_registry; native_registry.features.emplace("ure.scene.simulation", Version{1, 0}); const auto scene_binary = write_scene_ir_binary(archive); const auto scene_loaded = read_scene_ir_binary(scene_binary, native_registry); check(scene_loaded.ok() && scene_loaded.value->simulation_contract, "binary archive lost simulation contract"); const auto exploded = write_scene_ir_text(archive); const auto exploded_loaded = read_scene_ir_text(exploded, native_registry); check(exploded_loaded.ok() && exploded_loaded.value->simulation_contract, "text archive lost simulation contract"); std::cout << "Phase Q.8 simulation contract checks: " << (failures ? "FAILED" : "PASSED") << '\n'; return failures == 0 ? EXIT_SUCCESS : EXIT_FAILURE; }
