#include <algorithm>
#include <map>
#include <limits>
#include <set>
#include <flatbuffers/flatbuffers.h>
#include <flatbuffers/verifier.h>
#include <nlohmann/json.hpp>

#include <ure/native_simulation_contract.hpp>
#include <ure/native_scene_hash.hpp>

#include "ure_simulation_contract_v1_generated.h"

namespace ure::native_scene {
namespace {
namespace fb = ure::simulation::schema;
void diagnostic(ValidationReport& report, std::string code, DiagnosticSeverity severity, std::string path, std::string message) { report.diagnostics.push_back({std::move(code), severity, std::move(path), std::move(message), {}}); }
bool supported(const SolverDomainRequest& request, const SimulationCapabilityRegistry& capabilities) { const auto solver = capabilities.solvers.find(request.solver_id); return capabilities.domains.contains(request.domain) && solver != capabilities.solvers.end() && solver->second.major == request.solver_version.major && solver->second.minor >= request.solver_version.minor; }
fb::SimulationContractT to_schema(const NativeSimulationContract& value) {
    fb::SimulationContractT result; result.id = value.id; result.schema_version = std::make_unique<fb::Version>(value.schema_version.major, value.schema_version.minor); result.time = std::make_unique<fb::TimeSamplingT>(); result.time->start_tick = value.time.start_tick; result.time->end_tick = value.time.end_tick; result.time->ticks_per_second = value.time.ticks_per_second; result.time->step_ticks = value.time.step_ticks; result.time->synchronization_epoch = value.time.synchronization_epoch;
    auto domains = value.domains; std::ranges::sort(domains, {}, &SolverDomainRequest::id); for (const auto& source : domains) { auto item = std::make_unique<fb::DomainRequestT>(); item->id = source.id; item->domain = static_cast<fb::Domain>(source.domain); item->requirement = static_cast<fb::Requirement>(source.requirement); item->solver_id = source.solver_id; item->solver_version = std::make_unique<fb::Version>(source.solver_version.major, source.solver_version.minor); item->resources = source.resources; std::ranges::sort(item->resources); item->extension_owner = source.extension_owner; result.domains.push_back(std::move(item)); }
    auto coupling = value.coupling; std::ranges::sort(coupling, {}, &CouplingChannel::id); for (const auto& source : coupling) { auto item = std::make_unique<fb::CouplingChannelT>(); item->id = source.id; item->source_domain = source.source_domain; item->target_domain = source.target_domain; item->semantic = static_cast<fb::CouplingSemantic>(source.semantic); item->requirement = static_cast<fb::Requirement>(source.requirement); item->rate_numerator = source.rate_numerator; item->rate_denominator = source.rate_denominator; item->latency_ticks = source.latency_ticks; item->feedback = source.feedback; item->resource_id = source.resource_id; item->extension_owner = source.extension_owner; result.coupling.push_back(std::move(item)); }
    auto migrations = value.migrations; std::ranges::sort(migrations, {}, &SolverMigrationPolicy::domain_id); for (const auto& source : migrations) { auto item = std::make_unique<fb::MigrationPolicyT>(); item->domain_id = source.domain_id; item->minimum_source_version = std::make_unique<fb::Version>(source.minimum_source_version.major, source.minimum_source_version.minor); item->target_version = std::make_unique<fb::Version>(source.target_version.major, source.target_version.minor); item->migration_tool = source.migration_tool; item->allow_lossy = source.allow_lossy; result.migrations.push_back(std::move(item)); } return result;
}
NativeSimulationContract from_schema(const fb::SimulationContractT& source) {
    if (!source.schema_version || !source.time) throw std::invalid_argument("Incomplete URPC payload"); NativeSimulationContract value; value.id = source.id; value.schema_version = {source.schema_version->major(), source.schema_version->minor()}; value.time = {source.time->start_tick, source.time->end_tick, source.time->ticks_per_second, source.time->step_ticks, source.time->synchronization_epoch};
    for (const auto& item : source.domains) { if (!item || !item->solver_version) throw std::invalid_argument("Incomplete domain request"); value.domains.push_back({item->id, static_cast<SimulationDomain>(item->domain), static_cast<RequirementLevel>(item->requirement), item->solver_id, {item->solver_version->major(), item->solver_version->minor()}, item->resources, item->extension_owner}); }
    for (const auto& item : source.coupling) { if (!item) throw std::invalid_argument("Incomplete coupling channel"); value.coupling.push_back({item->id, item->source_domain, item->target_domain, static_cast<CouplingSemantic>(item->semantic), static_cast<RequirementLevel>(item->requirement), item->rate_numerator, item->rate_denominator, item->latency_ticks, item->feedback, item->resource_id, item->extension_owner}); }
    for (const auto& item : source.migrations) { if (!item || !item->minimum_source_version || !item->target_version) throw std::invalid_argument("Incomplete migration policy"); value.migrations.push_back({item->domain_id, {item->minimum_source_version->major(), item->minimum_source_version->minor()}, {item->target_version->major(), item->target_version->minor()}, item->migration_tool, item->allow_lossy}); } return value;
}
template <typename T> LoadResult<T> failure(std::string code, std::string message) { LoadResult<T> result; result.diagnostics.push_back({std::move(code), DiagnosticSeverity::Error, "/simulation", std::move(message), {}}); return result; }
nlohmann::ordered_json simulation_json(const NativeSimulationContract& value) { auto domains = nlohmann::ordered_json::array(); auto sorted_domains = value.domains; std::ranges::sort(sorted_domains, {}, &SolverDomainRequest::id); for (const auto& item : sorted_domains) { auto resources = item.resources; std::ranges::sort(resources); domains.push_back({{"domain", static_cast<unsigned>(item.domain)}, {"extension_owner", item.extension_owner}, {"id", item.id}, {"requirement", static_cast<unsigned>(item.requirement)}, {"resources", resources}, {"solver_id", item.solver_id}, {"solver_version", {{"major", item.solver_version.major}, {"minor", item.solver_version.minor}}}}); } auto coupling = nlohmann::ordered_json::array(); auto sorted_coupling = value.coupling; std::ranges::sort(sorted_coupling, {}, &CouplingChannel::id); for (const auto& item : sorted_coupling) coupling.push_back({{"extension_owner", item.extension_owner}, {"feedback", item.feedback}, {"id", item.id}, {"latency_ticks", item.latency_ticks}, {"rate_denominator", item.rate_denominator}, {"rate_numerator", item.rate_numerator}, {"requirement", static_cast<unsigned>(item.requirement)}, {"resource_id", item.resource_id}, {"semantic", static_cast<unsigned>(item.semantic)}, {"source_domain", item.source_domain}, {"target_domain", item.target_domain}}); auto migrations = nlohmann::ordered_json::array(); auto sorted_migrations = value.migrations; std::ranges::sort(sorted_migrations, {}, &SolverMigrationPolicy::domain_id); for (const auto& item : sorted_migrations) migrations.push_back({{"allow_lossy", item.allow_lossy}, {"domain_id", item.domain_id}, {"migration_tool", item.migration_tool}, {"minimum_source_version", {{"major", item.minimum_source_version.major}, {"minor", item.minimum_source_version.minor}}}, {"target_version", {{"major", item.target_version.major}, {"minor", item.target_version.minor}}}}); return {{"coupling", coupling}, {"domains", domains}, {"id", value.id}, {"migrations", migrations}, {"schema", kSimulationSchemaIdentity}, {"schema_version", {{"major", value.schema_version.major}, {"minor", value.schema_version.minor}}}, {"time", {{"end_tick", value.time.end_tick}, {"start_tick", value.time.start_tick}, {"step_ticks", value.time.step_ticks}, {"synchronization_epoch", value.time.synchronization_epoch}, {"ticks_per_second", value.time.ticks_per_second}}}}; }
NativeSimulationContract simulation_from_json(const nlohmann::ordered_json& root) { if (root.at("schema") != kSimulationSchemaIdentity) throw std::invalid_argument("Wrong simulation schema identity"); NativeSimulationContract value; value.id = root.at("id"); value.schema_version = {root.at("schema_version").at("major"), root.at("schema_version").at("minor")}; const auto& time = root.at("time"); value.time = {time.at("start_tick"), time.at("end_tick"), time.at("ticks_per_second"), time.at("step_ticks"), time.at("synchronization_epoch")}; for (const auto& item : root.at("domains")) value.domains.push_back({item.at("id"), static_cast<SimulationDomain>(item.at("domain").get<unsigned>()), static_cast<RequirementLevel>(item.at("requirement").get<unsigned>()), item.at("solver_id"), {item.at("solver_version").at("major"), item.at("solver_version").at("minor")}, item.at("resources").get<std::vector<std::string>>(), item.at("extension_owner")}); for (const auto& item : root.at("coupling")) value.coupling.push_back({item.at("id"), item.at("source_domain"), item.at("target_domain"), static_cast<CouplingSemantic>(item.at("semantic").get<unsigned>()), static_cast<RequirementLevel>(item.at("requirement").get<unsigned>()), item.at("rate_numerator"), item.at("rate_denominator"), item.at("latency_ticks"), item.at("feedback"), item.at("resource_id"), item.at("extension_owner")}); for (const auto& item : root.at("migrations")) value.migrations.push_back({item.at("domain_id"), {item.at("minimum_source_version").at("major"), item.at("minimum_source_version").at("minor")}, {item.at("target_version").at("major"), item.at("target_version").at("minor")}, item.at("migration_tool"), item.at("allow_lossy")}); return value; }
}

bool CompiledSimulationContract::ok() const { return physics.has_value() && std::ranges::none_of(diagnostics, [](const auto& item) { return item.severity == DiagnosticSeverity::Error; }); }

ValidationReport validate_simulation_contract(const NativeSimulationContract& value, const SimulationCapabilityRegistry& capabilities) {
    ValidationReport report; if (value.id.empty()) diagnostic(report, "URE-Q8-ID-001", DiagnosticSeverity::Error, "/simulation/id", "Simulation contract ID is empty"); if (value.schema_version.major != 1) diagnostic(report, "URE-Q8-VERSION-001", DiagnosticSeverity::Error, "/simulation/schema_version", "Unsupported schema major version");
    if (!value.time.ticks_per_second || !value.time.step_ticks || value.time.end_tick < value.time.start_tick) diagnostic(report, "URE-Q8-TIME-001", DiagnosticSeverity::Error, "/simulation/time", "Invalid rational time sampling");
    std::map<std::string, const SolverDomainRequest*> domains; std::map<std::string, std::string> resource_owners;
    for (const auto& domain : value.domains) { const std::string path = "/simulation/domains/" + domain.id; if (domain.id.empty() || !domains.emplace(domain.id, &domain).second) diagnostic(report, "URE-Q8-ID-002", DiagnosticSeverity::Error, path, "Domain IDs must be nonempty and unique"); if (domain.solver_id.empty() || domain.solver_version.major == 0) diagnostic(report, "URE-Q8-SOLVER-001", DiagnosticSeverity::Error, path, "Solver identity and version are required"); if (domain.domain == SimulationDomain::Extension && domain.extension_owner.empty()) diagnostic(report, "URE-Q8-EXTENSION-001", DiagnosticSeverity::Error, path, "Extension domain requires an owner"); if (!supported(domain, capabilities)) diagnostic(report, domain.requirement == RequirementLevel::Required ? "URE-Q8-CAPABILITY-001" : "URE-Q8-CAPABILITY-101", domain.requirement == RequirementLevel::Required ? DiagnosticSeverity::Error : DiagnosticSeverity::Warning, path, "Requested solver/domain is unsupported and retained"); for (const auto& resource : domain.resources) if (resource.empty() || !resource_owners.emplace(resource, domain.id).second) diagnostic(report, "URE-Q8-RESOURCE-001", DiagnosticSeverity::Error, path, "Resources must be nonempty and have one owning domain"); }
    std::map<std::string, int> state; std::map<std::string, std::vector<const CouplingChannel*>> edges;
    for (const auto& channel : value.coupling) {
        const std::string path = "/simulation/coupling/" + channel.id;
        if (channel.id.empty() || !domains.contains(channel.source_domain) || !domains.contains(channel.target_domain)) diagnostic(report, "URE-Q8-COUPLING-001", DiagnosticSeverity::Error, path, "Coupling endpoints are missing");
        if (!channel.rate_numerator || !channel.rate_denominator || channel.latency_ticks < 0) diagnostic(report, "URE-Q8-COUPLING-002", DiagnosticSeverity::Error, path, "Invalid coupling rate or latency");
        if (!channel.resource_id.empty() && !resource_owners.contains(channel.resource_id)) diagnostic(report, "URE-Q8-RESOURCE-002", DiagnosticSeverity::Error, path, "Coupling resource has no owning domain");
        if (channel.semantic == CouplingSemantic::Extension && channel.extension_owner.empty()) diagnostic(report, "URE-Q8-EXTENSION-002", DiagnosticSeverity::Error, path, "Extension coupling requires an owner");
        if (!capabilities.coupling_semantics.contains(channel.semantic)) diagnostic(report, channel.requirement == RequirementLevel::Required ? "URE-Q8-CAPABILITY-002" : "URE-Q8-CAPABILITY-102", channel.requirement == RequirementLevel::Required ? DiagnosticSeverity::Error : DiagnosticSeverity::Warning, path, "Unsupported coupling semantic retained");
        edges[channel.source_domain].push_back(&channel);
    }
    const auto visit = [&](const auto& self, const std::string& id, bool feedback_path) -> void { if (state[id] == 1) { if (!feedback_path) diagnostic(report, "URE-Q8-COUPLING-003", DiagnosticSeverity::Error, "/simulation/coupling", "Coupling cycle lacks explicit feedback consent"); return; } if (state[id] == 2) return; state[id] = 1; for (const auto* edge : edges[id]) self(self, edge->target_domain, feedback_path && edge->feedback); state[id] = 2; }; for (const auto& [id, domain] : domains) { (void)domain; state.clear(); visit(visit, id, true); }
    for (const auto& migration : value.migrations) { if (!domains.contains(migration.domain_id) || migration.target_version < migration.minimum_source_version || migration.migration_tool.empty()) diagnostic(report, "URE-Q8-MIGRATION-001", DiagnosticSeverity::Error, "/simulation/migrations", "Invalid solver migration policy"); }
    return report;
}

CompiledSimulationContract compile_simulation_contract(const NativeSimulationContract& value, const SimulationCapabilityRegistry& capabilities) {
    CompiledSimulationContract result; const auto validation = validate_simulation_contract(value, capabilities); result.diagnostics = validation.diagnostics; if (!validation.ok()) return result; PhysicsConfig physics; physics.dt = static_cast<float>(static_cast<double>(value.time.step_ticks) / static_cast<double>(value.time.ticks_per_second)); const std::uint64_t span = static_cast<std::uint64_t>(value.time.end_tick - value.time.start_tick); physics.total_frames = static_cast<int>(std::min<std::uint64_t>(span / value.time.step_ticks + 1, static_cast<std::uint64_t>(std::numeric_limits<int>::max()))); for (const auto& domain : value.domains) { if (!supported(domain, capabilities)) { result.retained_domains.push_back(domain); continue; } if (domain.domain == SimulationDomain::RigidBody) physics.enabled = true; else if (domain.domain == SimulationDomain::Fluid) { physics.enabled = true; physics.fluid.enabled = true; } else result.retained_domains.push_back(domain); } result.physics = physics; return result;
}

std::vector<std::uint8_t> write_simulation_contract_binary(const NativeSimulationContract& contract) { auto native = to_schema(contract); flatbuffers::FlatBufferBuilder builder; fb::FinishSimulationContractBuffer(builder, fb::SimulationContract::Pack(builder, &native)); return {builder.GetBufferPointer(), builder.GetBufferPointer() + builder.GetSize()}; }
LoadResult<NativeSimulationContract> read_simulation_contract_binary(std::span<const std::uint8_t> bytes) { flatbuffers::Verifier verifier(bytes.data(), bytes.size()); if (!fb::VerifySimulationContractBuffer(verifier)) return failure<NativeSimulationContract>("URE-Q8-SCHEMA-001", "Invalid URPC payload"); try { std::unique_ptr<fb::SimulationContractT> native(fb::GetSimulationContract(bytes.data())->UnPack()); LoadResult<NativeSimulationContract> result; result.value = from_schema(*native); return result; } catch (const std::exception& exception) { return failure<NativeSimulationContract>("URE-Q8-SCHEMA-002", exception.what()); } }
std::string simulation_contract_semantic_hash(const NativeSimulationContract& contract) { return sha256_hex(write_simulation_contract_binary(contract)); }
std::string write_simulation_contract_text(const NativeSimulationContract& contract) { return simulation_json(contract).dump(2) + "\n"; }
LoadResult<NativeSimulationContract> read_simulation_contract_text(std::string_view text) { try { LoadResult<NativeSimulationContract> result; result.value = simulation_from_json(nlohmann::ordered_json::parse(text)); return result; } catch (const std::exception& exception) { return failure<NativeSimulationContract>("URE-Q8-TEXT-001", exception.what()); } }

}
