#include <stddef.h>
#include <stdio.h>

#include <ultrarender/ure_loader.h>

#define PRINT_LAYOUT(type, format, ...) printf(#type "|%zu|%zu|" format "\\n", sizeof(type), _Alignof(type), __VA_ARGS__)

int main(void) {
    fputs("{\"schema\":\"ure.public.abi-layout/windows-x64/"
          "0.1\",\"layout_signature\":\"",
          stdout);
    PRINT_LAYOUT(ure_input_header_t, "%zu|%zu|%zu", offsetof(ure_input_header_t, type), offsetof(ure_input_header_t, size), offsetof(ure_input_header_t, next));
    PRINT_LAYOUT(ure_output_header_t, "%zu|%zu|%zu", offsetof(ure_output_header_t, type), offsetof(ure_output_header_t, size), offsetof(ure_output_header_t, next));
    PRINT_LAYOUT(ure_uuid_t, "%zu", offsetof(ure_uuid_t, bytes));
    PRINT_LAYOUT(ure_digest256_t, "%zu", offsetof(ure_digest256_t, bytes));
    PRINT_LAYOUT(ure_byte_span_t, "%zu|%zu", offsetof(ure_byte_span_t, data), offsetof(ure_byte_span_t, size));
    PRINT_LAYOUT(ure_mutable_byte_span_t, "%zu|%zu", offsetof(ure_mutable_byte_span_t, data), offsetof(ure_mutable_byte_span_t, size));
    PRINT_LAYOUT(ure_string_view_t, "%zu|%zu", offsetof(ure_string_view_t, data), offsetof(ure_string_view_t, size));
    PRINT_LAYOUT(ure_interface_table_header_t, "%zu|%zu|%zu", offsetof(ure_interface_table_header_t, struct_size), offsetof(ure_interface_table_header_t, version_major), offsetof(ure_interface_table_header_t, version_minor));
    PRINT_LAYOUT(ure_runtime_interface_t, "%zu", offsetof(ure_runtime_interface_t, header));
    PRINT_LAYOUT(ure_instance_create_info_t, "%zu|%zu|%zu|%zu|%zu", offsetof(ure_instance_create_info_t, header), offsetof(ure_instance_create_info_t, event_capacity), offsetof(ure_instance_create_info_t, required_capability_count), offsetof(ure_instance_create_info_t, required_capabilities), offsetof(ure_instance_create_info_t, reserved));
    PRINT_LAYOUT(ure_capability_query_t, "%zu|%zu|%zu|%zu|%zu", offsetof(ure_capability_query_t, header), offsetof(ure_capability_query_t, capability_id), offsetof(ure_capability_query_t, required), offsetof(ure_capability_query_t, request_enable), offsetof(ure_capability_query_t, reserved));
    PRINT_LAYOUT(ure_capability_descriptor_t, "%zu|%zu|%zu|%zu|%zu|%zu|%zu|%zu|%zu|%zu|%zu|%zu|%zu|%zu|%zu|%zu|%zu", offsetof(ure_capability_descriptor_t, header), offsetof(ure_capability_descriptor_t, capability_id), offsetof(ure_capability_descriptor_t, version_major), offsetof(ure_capability_descriptor_t, version_minor), offsetof(ure_capability_descriptor_t, version_patch), offsetof(ure_capability_descriptor_t, stability), offsetof(ure_capability_descriptor_t, maturity), offsetof(ure_capability_descriptor_t, runtime_state), offsetof(ure_capability_descriptor_t, enabled), offsetof(ure_capability_descriptor_t, applicable), offsetof(ure_capability_descriptor_t, dependency_count), offsetof(ure_capability_descriptor_t, thread_policy), offsetof(ure_capability_descriptor_t, limits_schema), offsetof(ure_capability_descriptor_t, dependencies), offsetof(ure_capability_descriptor_t, limits), offsetof(ure_capability_descriptor_t, reason), offsetof(ure_capability_descriptor_t, reserved));
    PRINT_LAYOUT(ure_error_info_t, "%zu|%zu|%zu|%zu|%zu|%zu|%zu|%zu|%zu|%zu|%zu", offsetof(ure_error_info_t, header), offsetof(ure_error_info_t, result), offsetof(ure_error_info_t, domain), offsetof(ure_error_info_t, detail), offsetof(ure_error_info_t, structured_detail_schema), offsetof(ure_error_info_t, reserved), offsetof(ure_error_info_t, message), offsetof(ure_error_info_t, structured_detail), offsetof(ure_error_info_t, cause), offsetof(ure_error_info_t, operation), offsetof(ure_error_info_t, build_digest));
    PRINT_LAYOUT(ure_operation_info_t, "%zu|%zu|%zu|%zu|%zu|%zu|%zu|%zu|%zu|%zu", offsetof(ure_operation_info_t, header), offsetof(ure_operation_info_t, state), offsetof(ure_operation_info_t, progress_available), offsetof(ure_operation_info_t, progress), offsetof(ure_operation_info_t, stage), offsetof(ure_operation_info_t, reserved), offsetof(ure_operation_info_t, completed_work), offsetof(ure_operation_info_t, total_work), offsetof(ure_operation_info_t, progress_sequence), offsetof(ure_operation_info_t, terminal_error));
    PRINT_LAYOUT(ure_event_record_t, "%zu|%zu|%zu|%zu|%zu|%zu|%zu|%zu|%zu|%zu|%zu|%zu|%zu|%zu", offsetof(ure_event_record_t, header), offsetof(ure_event_record_t, event_type), offsetof(ure_event_record_t, affected_classes), offsetof(ure_event_record_t, sequence), offsetof(ure_event_record_t, timestamp_ns), offsetof(ure_event_record_t, instance), offsetof(ure_event_record_t, operation), offsetof(ure_event_record_t, first_lost_sequence), offsetof(ure_event_record_t, last_lost_sequence), offsetof(ure_event_record_t, payload_schema), offsetof(ure_event_record_t, reserved), offsetof(ure_event_record_t, coalesced_count), offsetof(ure_event_record_t, payload), offsetof(ure_event_record_t, frame));
    PRINT_LAYOUT(ure_instance_frame_budget_t, "%zu|%zu|%zu|%zu", offsetof(ure_instance_frame_budget_t, header), offsetof(ure_instance_frame_budget_t, max_retained_frames), offsetof(ure_instance_frame_budget_t, reserved), offsetof(ure_instance_frame_budget_t, max_retained_bytes));
    PRINT_LAYOUT(ure_scene_budget_t, "%zu|%zu|%zu|%zu|%zu|%zu|%zu|%zu|%zu", offsetof(ure_scene_budget_t, header), offsetof(ure_scene_budget_t, max_content_bytes), offsetof(ure_scene_budget_t, max_uncompressed_bytes), offsetof(ure_scene_budget_t, max_resident_bytes), offsetof(ure_scene_budget_t, max_resource_count), offsetof(ure_scene_budget_t, max_object_count), offsetof(ure_scene_budget_t, max_nesting_depth), offsetof(ure_scene_budget_t, max_decompression_ratio), offsetof(ure_scene_budget_t, reserved));
    PRINT_LAYOUT(ure_native_scene_blob_t, "%zu|%zu|%zu|%zu|%zu|%zu|%zu|%zu|%zu|%zu|%zu|%zu", offsetof(ure_native_scene_blob_t, header), offsetof(ure_native_scene_blob_t, source_kind), offsetof(ure_native_scene_blob_t, format), offsetof(ure_native_scene_blob_t, bytes), offsetof(ure_native_scene_blob_t, path_utf8), offsetof(ure_native_scene_blob_t, package_scene_id), offsetof(ure_native_scene_blob_t, schema_min_major), offsetof(ure_native_scene_blob_t, schema_min_minor), offsetof(ure_native_scene_blob_t, schema_max_major), offsetof(ure_native_scene_blob_t, schema_max_minor), offsetof(ure_native_scene_blob_t, budget), offsetof(ure_native_scene_blob_t, reserved));
    PRINT_LAYOUT(ure_scene_transaction_t, "%zu|%zu|%zu|%zu|%zu|%zu|%zu|%zu|%zu|%zu|%zu", offsetof(ure_scene_transaction_t, header), offsetof(ure_scene_transaction_t, transaction_id), offsetof(ure_scene_transaction_t, base_revision), offsetof(ure_scene_transaction_t, payload_schema), offsetof(ure_scene_transaction_t, payload_version_major), offsetof(ure_scene_transaction_t, payload_version_minor), offsetof(ure_scene_transaction_t, max_operation_count), offsetof(ure_scene_transaction_t, max_payload_bytes), offsetof(ure_scene_transaction_t, payload), offsetof(ure_scene_transaction_t, payload_digest), offsetof(ure_scene_transaction_t, reserved));
    PRINT_LAYOUT(ure_scene_transaction_result_t, "%zu|%zu|%zu|%zu|%zu|%zu|%zu|%zu|%zu|%zu|%zu|%zu|%zu|%zu", offsetof(ure_scene_transaction_result_t, header), offsetof(ure_scene_transaction_result_t, transaction_id), offsetof(ure_scene_transaction_result_t, strategy), offsetof(ure_scene_transaction_result_t, reset_reason), offsetof(ure_scene_transaction_result_t, base_revision), offsetof(ure_scene_transaction_result_t, resulting_revision), offsetof(ure_scene_transaction_result_t, revision_identity), offsetof(ure_scene_transaction_result_t, semantic_digest), offsetof(ure_scene_transaction_result_t, applied_operation_count), offsetof(ure_scene_transaction_result_t, warning_count), offsetof(ure_scene_transaction_result_t, result_required), offsetof(ure_scene_transaction_result_t, result_written), offsetof(ure_scene_transaction_result_t, result_payload), offsetof(ure_scene_transaction_result_t, reserved));
    PRINT_LAYOUT(ure_scene_validation_result_t, "%zu|%zu|%zu|%zu|%zu|%zu|%zu|%zu|%zu|%zu|%zu|%zu|%zu|%zu|%zu|%zu", offsetof(ure_scene_validation_result_t, header), offsetof(ure_scene_validation_result_t, valid), offsetof(ure_scene_validation_result_t, error_count), offsetof(ure_scene_validation_result_t, warning_count), offsetof(ure_scene_validation_result_t, source_schema_major), offsetof(ure_scene_validation_result_t, source_schema_minor), offsetof(ure_scene_validation_result_t, diagnostics_capacity), offsetof(ure_scene_validation_result_t, diagnostics_required), offsetof(ure_scene_validation_result_t, diagnostics_written), offsetof(ure_scene_validation_result_t, diagnostics_data), offsetof(ure_scene_validation_result_t, blob_digest), offsetof(ure_scene_validation_result_t, semantic_digest), offsetof(ure_scene_validation_result_t, resource_manifest_digest), offsetof(ure_scene_validation_result_t, resource_count), offsetof(ure_scene_validation_result_t, object_count), offsetof(ure_scene_validation_result_t, reserved));
    PRINT_LAYOUT(ure_scene_revision_info_t, "%zu|%zu|%zu|%zu|%zu|%zu|%zu|%zu|%zu|%zu|%zu|%zu|%zu|%zu|%zu|%zu|%zu", offsetof(ure_scene_revision_info_t, header), offsetof(ure_scene_revision_info_t, revision), offsetof(ure_scene_revision_info_t, revision_identity), offsetof(ure_scene_revision_info_t, blob_digest), offsetof(ure_scene_revision_info_t, semantic_digest), offsetof(ure_scene_revision_info_t, resource_manifest_digest), offsetof(ure_scene_revision_info_t, source_schema_major), offsetof(ure_scene_revision_info_t, source_schema_minor), offsetof(ure_scene_revision_info_t, reset_reason), offsetof(ure_scene_revision_info_t, warning_count), offsetof(ure_scene_revision_info_t, loss_count), offsetof(ure_scene_revision_info_t, reserved32), offsetof(ure_scene_revision_info_t, resource_count), offsetof(ure_scene_revision_info_t, object_count), offsetof(ure_scene_revision_info_t, selected_package_scene), offsetof(ure_scene_revision_info_t, reserved), sizeof(((ure_scene_revision_info_t *)0)->reserved));
    PRINT_LAYOUT(ure_objective_envelope_t, "%zu|%zu|%zu|%zu|%zu|%zu|%zu|%zu|%zu|%zu|%zu|%zu|%zu|%zu|%zu", offsetof(ure_objective_envelope_t, header), offsetof(ure_objective_envelope_t, payload_schema), offsetof(ure_objective_envelope_t, payload_version_major), offsetof(ure_objective_envelope_t, payload_version_minor), offsetof(ure_objective_envelope_t, determinism_policy), offsetof(ure_objective_envelope_t, usage_policy), offsetof(ure_objective_envelope_t, output_count), offsetof(ure_objective_envelope_t, output_semantics), offsetof(ure_objective_envelope_t, wall_time_budget_ns), offsetof(ure_objective_envelope_t, memory_budget_bytes), offsetof(ure_objective_envelope_t, sample_budget), offsetof(ure_objective_envelope_t, latency_budget_ns), offsetof(ure_objective_envelope_t, payload), offsetof(ure_objective_envelope_t, payload_digest), offsetof(ure_objective_envelope_t, reserved));
    PRINT_LAYOUT(ure_session_info_t, "%zu|%zu|%zu|%zu|%zu|%zu|%zu|%zu|%zu|%zu|%zu", offsetof(ure_session_info_t, header), offsetof(ure_session_info_t, state), offsetof(ure_session_info_t, reset_reason), offsetof(ure_session_info_t, bound_scene_revision), offsetof(ure_session_info_t, scene_revision_identity), offsetof(ure_session_info_t, objective_identity), offsetof(ure_session_info_t, completed_samples), offsetof(ure_session_info_t, requested_samples), offsetof(ure_session_info_t, active_operation), offsetof(ure_session_info_t, latest_frame), offsetof(ure_session_info_t, reserved));
    PRINT_LAYOUT(ure_frame_info_t,
                 "%zu|%zu|%zu|%zu|%zu|%zu|%zu|%zu|%zu|%zu|%zu|%zu|%zu|%zu|%zu|%zu|%zu|%zu|"
                 "%zu|%zu|%zu",
                 offsetof(ure_frame_info_t, header), offsetof(ure_frame_info_t, frame_identity), offsetof(ure_frame_info_t, scene_revision_identity), offsetof(ure_frame_info_t, camera_revision_identity), offsetof(ure_frame_info_t, objective_identity), offsetof(ure_frame_info_t, estimator_identity), offsetof(ure_frame_info_t, provenance_identity), offsetof(ure_frame_info_t, operation), offsetof(ure_frame_info_t, sample_begin), offsetof(ure_frame_info_t, sample_count), offsetof(ure_frame_info_t, timestamp_ns), offsetof(ure_frame_info_t, retained_bytes), offsetof(ure_frame_info_t, width), offsetof(ure_frame_info_t, height), offsetof(ure_frame_info_t, completion), offsetof(ure_frame_info_t, plane_count), offsetof(ure_frame_info_t, dirty_x), offsetof(ure_frame_info_t, dirty_y), offsetof(ure_frame_info_t, dirty_width), offsetof(ure_frame_info_t, dirty_height), offsetof(ure_frame_info_t, reserved));
    PRINT_LAYOUT(ure_frame_plane_info_t,
                 "%zu|%zu|%zu|%zu|%zu|%zu|%zu|%zu|%zu|%zu|%zu|%zu|%zu|%zu|%zu|%"
                 "zu|%zu|%zu|%zu",
                 offsetof(ure_frame_plane_info_t, header), offsetof(ure_frame_plane_info_t, plane_schema), offsetof(ure_frame_plane_info_t, scalar_type), offsetof(ure_frame_plane_info_t, component_layout), offsetof(ure_frame_plane_info_t, normalization), offsetof(ure_frame_plane_info_t, width), offsetof(ure_frame_plane_info_t, height), offsetof(ure_frame_plane_info_t, depth), offsetof(ure_frame_plane_info_t, element_stride), offsetof(ure_frame_plane_info_t, row_stride), offsetof(ure_frame_plane_info_t, slice_stride), offsetof(ure_frame_plane_info_t, byte_extent), offsetof(ure_frame_plane_info_t, observable_identity), offsetof(ure_frame_plane_info_t, unit_identity), offsetof(ure_frame_plane_info_t, measure_identity), offsetof(ure_frame_plane_info_t, time_identity), offsetof(ure_frame_plane_info_t, uncertainty_identity), offsetof(ure_frame_plane_info_t, provenance_identity), offsetof(ure_frame_plane_info_t, reserved));
    PRINT_LAYOUT(ure_frame_map_t, "%zu|%zu|%zu|%zu|%zu|%zu|%zu|%zu|%zu", offsetof(ure_frame_map_t, header), offsetof(ure_frame_map_t, frame), offsetof(ure_frame_map_t, plane_index), offsetof(ure_frame_map_t, reserved), offsetof(ure_frame_map_t, data), offsetof(ure_frame_map_t, row_stride), offsetof(ure_frame_map_t, slice_stride), offsetof(ure_frame_map_t, byte_extent), offsetof(ure_frame_map_t, map_token));
    PRINT_LAYOUT(ure_frame_copy_info_t, "%zu|%zu|%zu|%zu|%zu|%zu|%zu|%zu", offsetof(ure_frame_copy_info_t, header), offsetof(ure_frame_copy_info_t, frame), offsetof(ure_frame_copy_info_t, plane_index), offsetof(ure_frame_copy_info_t, reserved), offsetof(ure_frame_copy_info_t, destination), offsetof(ure_frame_copy_info_t, destination_size), offsetof(ure_frame_copy_info_t, destination_row_stride), offsetof(ure_frame_copy_info_t, destination_slice_stride));
    PRINT_LAYOUT(ure_instance_interface_t, "%zu|%zu|%zu|%zu|%zu", offsetof(ure_instance_interface_t, header), offsetof(ure_instance_interface_t, retain), offsetof(ure_instance_interface_t, release), offsetof(ure_instance_interface_t, close), offsetof(ure_instance_interface_t, query_capability));
    PRINT_LAYOUT(ure_error_interface_t, "%zu|%zu|%zu|%zu", offsetof(ure_error_interface_t, header), offsetof(ure_error_interface_t, retain), offsetof(ure_error_interface_t, release), offsetof(ure_error_interface_t, get_info));
    PRINT_LAYOUT(ure_operation_interface_t, "%zu|%zu|%zu|%zu|%zu|%zu", offsetof(ure_operation_interface_t, header), offsetof(ure_operation_interface_t, retain), offsetof(ure_operation_interface_t, release), offsetof(ure_operation_interface_t, get_info), offsetof(ure_operation_interface_t, wait), offsetof(ure_operation_interface_t, request_cancel));
    PRINT_LAYOUT(ure_event_interface_t, "%zu|%zu|%zu", offsetof(ure_event_interface_t, header), offsetof(ure_event_interface_t, poll), offsetof(ure_event_interface_t, wait));
    PRINT_LAYOUT(ure_frame_interface_t, "%zu|%zu|%zu|%zu|%zu|%zu|%zu|%zu", offsetof(ure_frame_interface_t, header), offsetof(ure_frame_interface_t, retain), offsetof(ure_frame_interface_t, release), offsetof(ure_frame_interface_t, get_info), offsetof(ure_frame_interface_t, get_plane_info), offsetof(ure_frame_interface_t, map_plane_read), offsetof(ure_frame_interface_t, unmap_plane), offsetof(ure_frame_interface_t, copy_plane));
    PRINT_LAYOUT(ure_scene_interface_t, "%zu|%zu|%zu|%zu|%zu|%zu|%zu|%zu", offsetof(ure_scene_interface_t, header), offsetof(ure_scene_interface_t, validate), offsetof(ure_scene_interface_t, create), offsetof(ure_scene_interface_t, replace), offsetof(ure_scene_interface_t, retain), offsetof(ure_scene_interface_t, release), offsetof(ure_scene_interface_t, get_revision), offsetof(ure_scene_interface_t, apply_transaction));
    PRINT_LAYOUT(ure_session_interface_t, "%zu|%zu|%zu|%zu|%zu|%zu|%zu|%zu|%zu|%zu|%zu|%zu", offsetof(ure_session_interface_t, header), offsetof(ure_session_interface_t, create), offsetof(ure_session_interface_t, retain), offsetof(ure_session_interface_t, release), offsetof(ure_session_interface_t, close), offsetof(ure_session_interface_t, get_info), offsetof(ure_session_interface_t, bind_scene), offsetof(ure_session_interface_t, start), offsetof(ure_session_interface_t, pause), offsetof(ure_session_interface_t, resume), offsetof(ure_session_interface_t, reset), offsetof(ure_session_interface_t, acquire_frame));
    PRINT_LAYOUT(ure_bootstrap_diagnostic_t, "%zu|%zu|%zu|%zu|%zu|%zu|%zu|%zu|%zu|%zu", offsetof(ure_bootstrap_diagnostic_t, header), offsetof(ure_bootstrap_diagnostic_t, result), offsetof(ure_bootstrap_diagnostic_t, domain), offsetof(ure_bootstrap_diagnostic_t, detail), offsetof(ure_bootstrap_diagnostic_t, message_capacity), offsetof(ure_bootstrap_diagnostic_t, message_required), offsetof(ure_bootstrap_diagnostic_t, message_written), offsetof(ure_bootstrap_diagnostic_t, reserved), offsetof(ure_bootstrap_diagnostic_t, message_data), sizeof(((ure_bootstrap_diagnostic_t *)0)->message_data));
    PRINT_LAYOUT(ure_runtime_manifest_request_t, "%zu|%zu|%zu|%zu|%zu|%zu|%zu", offsetof(ure_runtime_manifest_request_t, header), offsetof(ure_runtime_manifest_request_t, minimum_major), offsetof(ure_runtime_manifest_request_t, minimum_minor), offsetof(ure_runtime_manifest_request_t, maximum_major), offsetof(ure_runtime_manifest_request_t, maximum_minor), offsetof(ure_runtime_manifest_request_t, expected_registry_digest), offsetof(ure_runtime_manifest_request_t, reserved));
    PRINT_LAYOUT(ure_runtime_manifest_t, "%zu|%zu|%zu|%zu|%zu|%zu|%zu|%zu", offsetof(ure_runtime_manifest_t, header), offsetof(ure_runtime_manifest_t, runtime_major), offsetof(ure_runtime_manifest_t, runtime_minor), offsetof(ure_runtime_manifest_t, runtime_patch), offsetof(ure_runtime_manifest_t, reserved), offsetof(ure_runtime_manifest_t, registry_digest), offsetof(ure_runtime_manifest_t, runtime_identity), offsetof(ure_runtime_manifest_t, abi_manifest_json));
    PRINT_LAYOUT(ure_interface_query_t, "%zu|%zu|%zu|%zu|%zu|%zu|%zu", offsetof(ure_interface_query_t, header), offsetof(ure_interface_query_t, interface_id), offsetof(ure_interface_query_t, minimum_major), offsetof(ure_interface_query_t, minimum_minor), offsetof(ure_interface_query_t, maximum_major), offsetof(ure_interface_query_t, maximum_minor), offsetof(ure_interface_query_t, reserved));
    PRINT_LAYOUT(ure_interface_response_t, "%zu|%zu|%zu|%zu|%zu|%zu|%zu", offsetof(ure_interface_response_t, header), offsetof(ure_interface_response_t, interface_id), offsetof(ure_interface_response_t, version_major), offsetof(ure_interface_response_t, version_minor), offsetof(ure_interface_response_t, table_size), offsetof(ure_interface_response_t, table), offsetof(ure_interface_response_t, reserved));
    puts("\"}");
    return 0;
}
