#include <cstddef>
#include <cstdio>

#include <ultrarender/ure_loader.h>

#define PRINT_LAYOUT(type, format, ...) std::printf(#type "|%zu|%zu|" format "\\n", sizeof(type), alignof(type), __VA_ARGS__)

int main() {
    std::fputs("{\"schema\":\"ure.public.abi-layout/windows-x64/"
               "0.1\",\"layout_signature\":\"",
               stdout);
    PRINT_LAYOUT(ure_input_header_t, "%zu|%zu|%zu", offsetof(ure_input_header_t, type), offsetof(ure_input_header_t, size), offsetof(ure_input_header_t, next));
    PRINT_LAYOUT(ure_output_header_t, "%zu|%zu|%zu", offsetof(ure_output_header_t, type), offsetof(ure_output_header_t, size), offsetof(ure_output_header_t, next));
    PRINT_LAYOUT(ure_uuid_t, "%zu", offsetof(ure_uuid_t, bytes));
    PRINT_LAYOUT(ure_digest256_t, "%zu", offsetof(ure_digest256_t, bytes));
    PRINT_LAYOUT(ure_byte_span_t, "%zu|%zu", offsetof(ure_byte_span_t, data), offsetof(ure_byte_span_t, size));
    PRINT_LAYOUT(ure_mutable_byte_span_t, "%zu|%zu", offsetof(ure_mutable_byte_span_t, data), offsetof(ure_mutable_byte_span_t, size));
    PRINT_LAYOUT(ure_string_view_t, "%zu|%zu", offsetof(ure_string_view_t, data), offsetof(ure_string_view_t, size));
    PRINT_LAYOUT(ure_interface_table_header_t, "%zu|%zu|%zu", offsetof(ure_interface_table_header_t, struct_size), offsetof(ure_interface_table_header_t, version_major), offsetof(ure_interface_table_header_t, version_minor));
    PRINT_LAYOUT(ure_runtime_interface_t, "%zu", offsetof(ure_runtime_interface_t, header));
    PRINT_LAYOUT(ure_instance_create_info_t, "%zu|%zu|%zu|%zu|%zu", offsetof(ure_instance_create_info_t, header), offsetof(ure_instance_create_info_t, event_capacity), offsetof(ure_instance_create_info_t, required_capability_count), offsetof(ure_instance_create_info_t, required_capabilities), offsetof(ure_instance_create_info_t, reserved));
    PRINT_LAYOUT(ure_capability_query_t, "%zu|%zu|%zu|%zu|%zu", offsetof(ure_capability_query_t, header), offsetof(ure_capability_query_t, capability_id), offsetof(ure_capability_query_t, required), offsetof(ure_capability_query_t, request_enable), offsetof(ure_capability_query_t, reserved));
    PRINT_LAYOUT(ure_capability_descriptor_t, "%zu|%zu|%zu|%zu|%zu|%zu|%zu|%zu|%zu|%zu|%zu|%zu|%zu|%zu|%zu|%zu|%zu", offsetof(ure_capability_descriptor_t, header), offsetof(ure_capability_descriptor_t, capability_id), offsetof(ure_capability_descriptor_t, version_major), offsetof(ure_capability_descriptor_t, version_minor), offsetof(ure_capability_descriptor_t, version_patch), offsetof(ure_capability_descriptor_t, stability), offsetof(ure_capability_descriptor_t, maturity), offsetof(ure_capability_descriptor_t, runtime_state), offsetof(ure_capability_descriptor_t, enabled), offsetof(ure_capability_descriptor_t, applicable), offsetof(ure_capability_descriptor_t, dependency_count), offsetof(ure_capability_descriptor_t, thread_policy), offsetof(ure_capability_descriptor_t, limits_schema), offsetof(ure_capability_descriptor_t, dependencies), offsetof(ure_capability_descriptor_t, limits), offsetof(ure_capability_descriptor_t, reason), offsetof(ure_capability_descriptor_t, reserved));
    PRINT_LAYOUT(ure_error_info_t, "%zu|%zu|%zu|%zu|%zu|%zu|%zu|%zu|%zu|%zu|%zu", offsetof(ure_error_info_t, header), offsetof(ure_error_info_t, result), offsetof(ure_error_info_t, domain), offsetof(ure_error_info_t, detail), offsetof(ure_error_info_t, structured_detail_schema), offsetof(ure_error_info_t, reserved), offsetof(ure_error_info_t, message), offsetof(ure_error_info_t, structured_detail), offsetof(ure_error_info_t, cause), offsetof(ure_error_info_t, operation), offsetof(ure_error_info_t, build_digest));
    PRINT_LAYOUT(ure_operation_info_t, "%zu|%zu|%zu|%zu|%zu|%zu|%zu|%zu|%zu|%zu", offsetof(ure_operation_info_t, header), offsetof(ure_operation_info_t, state), offsetof(ure_operation_info_t, progress_available), offsetof(ure_operation_info_t, progress), offsetof(ure_operation_info_t, stage), offsetof(ure_operation_info_t, reserved), offsetof(ure_operation_info_t, completed_work), offsetof(ure_operation_info_t, total_work), offsetof(ure_operation_info_t, progress_sequence), offsetof(ure_operation_info_t, terminal_error));
    PRINT_LAYOUT(ure_event_record_t, "%zu|%zu|%zu|%zu|%zu|%zu|%zu|%zu|%zu|%zu|%zu|%zu|%zu|%zu", offsetof(ure_event_record_t, header), offsetof(ure_event_record_t, event_type), offsetof(ure_event_record_t, affected_classes), offsetof(ure_event_record_t, sequence), offsetof(ure_event_record_t, timestamp_ns), offsetof(ure_event_record_t, instance), offsetof(ure_event_record_t, operation), offsetof(ure_event_record_t, first_lost_sequence), offsetof(ure_event_record_t, last_lost_sequence), offsetof(ure_event_record_t, payload_schema), offsetof(ure_event_record_t, reserved), offsetof(ure_event_record_t, coalesced_count), offsetof(ure_event_record_t, payload), offsetof(ure_event_record_t, frame));
    PRINT_LAYOUT(ure_instance_frame_budget_t, "%zu|%zu|%zu|%zu", offsetof(ure_instance_frame_budget_t, header), offsetof(ure_instance_frame_budget_t, max_retained_frames), offsetof(ure_instance_frame_budget_t, reserved), offsetof(ure_instance_frame_budget_t, max_retained_bytes));
    PRINT_LAYOUT(ure_frame_info_t,
                 "%zu|%zu|%zu|%zu|%zu|%zu|%zu|%zu|%zu|%zu|%zu|%zu|%zu|%zu|%zu|%zu|%zu|%zu|"
                 "%zu|%zu|%zu",
                 offsetof(ure_frame_info_t, header), offsetof(ure_frame_info_t, frame_identity), offsetof(ure_frame_info_t, scene_revision_identity), offsetof(ure_frame_info_t, camera_revision_identity), offsetof(ure_frame_info_t, objective_identity), offsetof(ure_frame_info_t, estimator_identity), offsetof(ure_frame_info_t, provenance_identity), offsetof(ure_frame_info_t, operation), offsetof(ure_frame_info_t, sample_begin), offsetof(ure_frame_info_t, sample_count), offsetof(ure_frame_info_t, timestamp_ns), offsetof(ure_frame_info_t, retained_bytes), offsetof(ure_frame_info_t, width), offsetof(ure_frame_info_t, height), offsetof(ure_frame_info_t, completion), offsetof(ure_frame_info_t, plane_count), offsetof(ure_frame_info_t, dirty_x), offsetof(ure_frame_info_t, dirty_y), offsetof(ure_frame_info_t, dirty_width), offsetof(ure_frame_info_t, dirty_height), offsetof(ure_frame_info_t, reserved));
    PRINT_LAYOUT(ure_frame_plane_info_t,
                 "%zu|%zu|%zu|%zu|%zu|%zu|%zu|%zu|%zu|%zu|%zu|%zu|%zu|%zu|%zu|%"
                 "zu|%zu|%zu|%zu",
                 offsetof(ure_frame_plane_info_t, header), offsetof(ure_frame_plane_info_t, plane_schema), offsetof(ure_frame_plane_info_t, scalar_type), offsetof(ure_frame_plane_info_t, component_layout), offsetof(ure_frame_plane_info_t, normalization), offsetof(ure_frame_plane_info_t, width), offsetof(ure_frame_plane_info_t, height), offsetof(ure_frame_plane_info_t, depth), offsetof(ure_frame_plane_info_t, element_stride), offsetof(ure_frame_plane_info_t, row_stride), offsetof(ure_frame_plane_info_t, slice_stride), offsetof(ure_frame_plane_info_t, byte_extent), offsetof(ure_frame_plane_info_t, observable_identity), offsetof(ure_frame_plane_info_t, unit_identity), offsetof(ure_frame_plane_info_t, measure_identity), offsetof(ure_frame_plane_info_t, time_identity), offsetof(ure_frame_plane_info_t, uncertainty_identity), offsetof(ure_frame_plane_info_t, provenance_identity), offsetof(ure_frame_plane_info_t, reserved));
    PRINT_LAYOUT(ure_frame_map_t, "%zu|%zu|%zu|%zu|%zu|%zu|%zu|%zu|%zu", offsetof(ure_frame_map_t, header), offsetof(ure_frame_map_t, frame), offsetof(ure_frame_map_t, plane_index), offsetof(ure_frame_map_t, reserved), offsetof(ure_frame_map_t, data), offsetof(ure_frame_map_t, row_stride), offsetof(ure_frame_map_t, slice_stride), offsetof(ure_frame_map_t, byte_extent), offsetof(ure_frame_map_t, map_token));
    PRINT_LAYOUT(ure_frame_copy_info_t, "%zu|%zu|%zu|%zu|%zu|%zu|%zu|%zu", offsetof(ure_frame_copy_info_t, header), offsetof(ure_frame_copy_info_t, frame), offsetof(ure_frame_copy_info_t, plane_index), offsetof(ure_frame_copy_info_t, reserved), offsetof(ure_frame_copy_info_t, destination), offsetof(ure_frame_copy_info_t, destination_size), offsetof(ure_frame_copy_info_t, destination_row_stride), offsetof(ure_frame_copy_info_t, destination_slice_stride));
    PRINT_LAYOUT(ure_instance_interface_t, "%zu|%zu|%zu|%zu|%zu", offsetof(ure_instance_interface_t, header), offsetof(ure_instance_interface_t, retain), offsetof(ure_instance_interface_t, release), offsetof(ure_instance_interface_t, close), offsetof(ure_instance_interface_t, query_capability));
    PRINT_LAYOUT(ure_error_interface_t, "%zu|%zu|%zu|%zu", offsetof(ure_error_interface_t, header), offsetof(ure_error_interface_t, retain), offsetof(ure_error_interface_t, release), offsetof(ure_error_interface_t, get_info));
    PRINT_LAYOUT(ure_operation_interface_t, "%zu|%zu|%zu|%zu|%zu|%zu", offsetof(ure_operation_interface_t, header), offsetof(ure_operation_interface_t, retain), offsetof(ure_operation_interface_t, release), offsetof(ure_operation_interface_t, get_info), offsetof(ure_operation_interface_t, wait), offsetof(ure_operation_interface_t, request_cancel));
    PRINT_LAYOUT(ure_event_interface_t, "%zu|%zu|%zu", offsetof(ure_event_interface_t, header), offsetof(ure_event_interface_t, poll), offsetof(ure_event_interface_t, wait));
    PRINT_LAYOUT(ure_frame_interface_t, "%zu|%zu|%zu|%zu|%zu|%zu|%zu|%zu", offsetof(ure_frame_interface_t, header), offsetof(ure_frame_interface_t, retain), offsetof(ure_frame_interface_t, release), offsetof(ure_frame_interface_t, get_info), offsetof(ure_frame_interface_t, get_plane_info), offsetof(ure_frame_interface_t, map_plane_read), offsetof(ure_frame_interface_t, unmap_plane), offsetof(ure_frame_interface_t, copy_plane));
    PRINT_LAYOUT(ure_bootstrap_diagnostic_t, "%zu|%zu|%zu|%zu|%zu|%zu|%zu|%zu|%zu|%zu", offsetof(ure_bootstrap_diagnostic_t, header), offsetof(ure_bootstrap_diagnostic_t, result), offsetof(ure_bootstrap_diagnostic_t, domain), offsetof(ure_bootstrap_diagnostic_t, detail), offsetof(ure_bootstrap_diagnostic_t, message_capacity), offsetof(ure_bootstrap_diagnostic_t, message_required), offsetof(ure_bootstrap_diagnostic_t, message_written), offsetof(ure_bootstrap_diagnostic_t, reserved), offsetof(ure_bootstrap_diagnostic_t, message_data), sizeof(((ure_bootstrap_diagnostic_t *)nullptr)->message_data));
    PRINT_LAYOUT(ure_runtime_manifest_request_t, "%zu|%zu|%zu|%zu|%zu|%zu|%zu", offsetof(ure_runtime_manifest_request_t, header), offsetof(ure_runtime_manifest_request_t, minimum_major), offsetof(ure_runtime_manifest_request_t, minimum_minor), offsetof(ure_runtime_manifest_request_t, maximum_major), offsetof(ure_runtime_manifest_request_t, maximum_minor), offsetof(ure_runtime_manifest_request_t, expected_registry_digest), offsetof(ure_runtime_manifest_request_t, reserved));
    PRINT_LAYOUT(ure_runtime_manifest_t, "%zu|%zu|%zu|%zu|%zu|%zu|%zu|%zu", offsetof(ure_runtime_manifest_t, header), offsetof(ure_runtime_manifest_t, runtime_major), offsetof(ure_runtime_manifest_t, runtime_minor), offsetof(ure_runtime_manifest_t, runtime_patch), offsetof(ure_runtime_manifest_t, reserved), offsetof(ure_runtime_manifest_t, registry_digest), offsetof(ure_runtime_manifest_t, runtime_identity), offsetof(ure_runtime_manifest_t, abi_manifest_json));
    PRINT_LAYOUT(ure_interface_query_t, "%zu|%zu|%zu|%zu|%zu|%zu|%zu", offsetof(ure_interface_query_t, header), offsetof(ure_interface_query_t, interface_id), offsetof(ure_interface_query_t, minimum_major), offsetof(ure_interface_query_t, minimum_minor), offsetof(ure_interface_query_t, maximum_major), offsetof(ure_interface_query_t, maximum_minor), offsetof(ure_interface_query_t, reserved));
    PRINT_LAYOUT(ure_interface_response_t, "%zu|%zu|%zu|%zu|%zu|%zu|%zu", offsetof(ure_interface_response_t, header), offsetof(ure_interface_response_t, interface_id), offsetof(ure_interface_response_t, version_major), offsetof(ure_interface_response_t, version_minor), offsetof(ure_interface_response_t, table_size), offsetof(ure_interface_response_t, table), offsetof(ure_interface_response_t, reserved));
    std::puts("\"}");
    return 0;
}
