if(EXISTS "E:/Render Engine/build_gui/tests/integration_tests[1]_tests.cmake")
  include("E:/Render Engine/build_gui/tests/integration_tests[1]_tests.cmake")
else()
  add_test(integration_tests_NOT_BUILT integration_tests_NOT_BUILT)
endif()
