add_test([=[VectorTest.Constructor]=]  [==[E:/Render Engine/build_gui/tests/Release/unit_tests.exe]==] [==[--gtest_filter=VectorTest.Constructor]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[VectorTest.Constructor]=]  PROPERTIES WORKING_DIRECTORY [==[E:/Render Engine/build_gui/tests]==] SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[VectorTest.Addition]=]  [==[E:/Render Engine/build_gui/tests/Release/unit_tests.exe]==] [==[--gtest_filter=VectorTest.Addition]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[VectorTest.Addition]=]  PROPERTIES WORKING_DIRECTORY [==[E:/Render Engine/build_gui/tests]==] SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[VectorTest.Subtraction]=]  [==[E:/Render Engine/build_gui/tests/Release/unit_tests.exe]==] [==[--gtest_filter=VectorTest.Subtraction]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[VectorTest.Subtraction]=]  PROPERTIES WORKING_DIRECTORY [==[E:/Render Engine/build_gui/tests]==] SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[VectorTest.ScalarMultiplication]=]  [==[E:/Render Engine/build_gui/tests/Release/unit_tests.exe]==] [==[--gtest_filter=VectorTest.ScalarMultiplication]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[VectorTest.ScalarMultiplication]=]  PROPERTIES WORKING_DIRECTORY [==[E:/Render Engine/build_gui/tests]==] SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[VectorTest.DotProduct]=]  [==[E:/Render Engine/build_gui/tests/Release/unit_tests.exe]==] [==[--gtest_filter=VectorTest.DotProduct]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[VectorTest.DotProduct]=]  PROPERTIES WORKING_DIRECTORY [==[E:/Render Engine/build_gui/tests]==] SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[VectorTest.CrossProduct]=]  [==[E:/Render Engine/build_gui/tests/Release/unit_tests.exe]==] [==[--gtest_filter=VectorTest.CrossProduct]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[VectorTest.CrossProduct]=]  PROPERTIES WORKING_DIRECTORY [==[E:/Render Engine/build_gui/tests]==] SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[VectorTest.Normalization]=]  [==[E:/Render Engine/build_gui/tests/Release/unit_tests.exe]==] [==[--gtest_filter=VectorTest.Normalization]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[VectorTest.Normalization]=]  PROPERTIES WORKING_DIRECTORY [==[E:/Render Engine/build_gui/tests]==] SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[MatrixTest.Identity]=]  [==[E:/Render Engine/build_gui/tests/Release/unit_tests.exe]==] [==[--gtest_filter=MatrixTest.Identity]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[MatrixTest.Identity]=]  PROPERTIES WORKING_DIRECTORY [==[E:/Render Engine/build_gui/tests]==] SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[MatrixTest.ManualTranslation]=]  [==[E:/Render Engine/build_gui/tests/Release/unit_tests.exe]==] [==[--gtest_filter=MatrixTest.ManualTranslation]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[MatrixTest.ManualTranslation]=]  PROPERTIES WORKING_DIRECTORY [==[E:/Render Engine/build_gui/tests]==] SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ImageSaverTest.SaveBmpLinear]=]  [==[E:/Render Engine/build_gui/tests/Release/unit_tests.exe]==] [==[--gtest_filter=ImageSaverTest.SaveBmpLinear]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ImageSaverTest.SaveBmpLinear]=]  PROPERTIES WORKING_DIRECTORY [==[E:/Render Engine/build_gui/tests]==] SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ImageSaverTest.SaveBmpReinhard]=]  [==[E:/Render Engine/build_gui/tests/Release/unit_tests.exe]==] [==[--gtest_filter=ImageSaverTest.SaveBmpReinhard]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ImageSaverTest.SaveBmpReinhard]=]  PROPERTIES WORKING_DIRECTORY [==[E:/Render Engine/build_gui/tests]==] SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ImageSaverTest.SaveBmpACES]=]  [==[E:/Render Engine/build_gui/tests/Release/unit_tests.exe]==] [==[--gtest_filter=ImageSaverTest.SaveBmpACES]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ImageSaverTest.SaveBmpACES]=]  PROPERTIES WORKING_DIRECTORY [==[E:/Render Engine/build_gui/tests]==] SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ImageSaverTest.SaveBmpExposure]=]  [==[E:/Render Engine/build_gui/tests/Release/unit_tests.exe]==] [==[--gtest_filter=ImageSaverTest.SaveBmpExposure]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ImageSaverTest.SaveBmpExposure]=]  PROPERTIES WORKING_DIRECTORY [==[E:/Render Engine/build_gui/tests]==] SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[RayTest.Constructor]=]  [==[E:/Render Engine/build_gui/tests/Release/unit_tests.exe]==] [==[--gtest_filter=RayTest.Constructor]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[RayTest.Constructor]=]  PROPERTIES WORKING_DIRECTORY [==[E:/Render Engine/build_gui/tests]==] SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[RayTest.At]=]  [==[E:/Render Engine/build_gui/tests/Release/unit_tests.exe]==] [==[--gtest_filter=RayTest.At]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[RayTest.At]=]  PROPERTIES WORKING_DIRECTORY [==[E:/Render Engine/build_gui/tests]==] SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[AABBTest.Constructor]=]  [==[E:/Render Engine/build_gui/tests/Release/unit_tests.exe]==] [==[--gtest_filter=AABBTest.Constructor]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[AABBTest.Constructor]=]  PROPERTIES WORKING_DIRECTORY [==[E:/Render Engine/build_gui/tests]==] SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[AABBTest.ExpandPoint]=]  [==[E:/Render Engine/build_gui/tests/Release/unit_tests.exe]==] [==[--gtest_filter=AABBTest.ExpandPoint]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[AABBTest.ExpandPoint]=]  PROPERTIES WORKING_DIRECTORY [==[E:/Render Engine/build_gui/tests]==] SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[AABBTest.Intersect]=]  [==[E:/Render Engine/build_gui/tests/Release/unit_tests.exe]==] [==[--gtest_filter=AABBTest.Intersect]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[AABBTest.Intersect]=]  PROPERTIES WORKING_DIRECTORY [==[E:/Render Engine/build_gui/tests]==] SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[AABBTest.NoIntersect]=]  [==[E:/Render Engine/build_gui/tests/Release/unit_tests.exe]==] [==[--gtest_filter=AABBTest.NoIntersect]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[AABBTest.NoIntersect]=]  PROPERTIES WORKING_DIRECTORY [==[E:/Render Engine/build_gui/tests]==] SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set(  unit_tests_TESTS VectorTest.Constructor VectorTest.Addition VectorTest.Subtraction VectorTest.ScalarMultiplication VectorTest.DotProduct VectorTest.CrossProduct VectorTest.Normalization MatrixTest.Identity MatrixTest.ManualTranslation ImageSaverTest.SaveBmpLinear ImageSaverTest.SaveBmpReinhard ImageSaverTest.SaveBmpACES ImageSaverTest.SaveBmpExposure RayTest.Constructor RayTest.At AABBTest.Constructor AABBTest.ExpandPoint AABBTest.Intersect AABBTest.NoIntersect)
