if(EXISTS "E:/Render Engine/build_vs/tests/unit_tests[1]_tests.cmake")
  include("E:/Render Engine/build_vs/tests/unit_tests[1]_tests.cmake")
else()
  add_test(unit_tests_NOT_BUILT unit_tests_NOT_BUILT)
endif()
