param(
    [string]$RepoRoot = (Resolve-Path (Join-Path $PSScriptRoot "..")).Path
)

$ErrorActionPreference = "Stop"

function Assert-Contains {
    param(
        [string]$Path,
        [string]$Pattern,
        [string]$Label
    )
    $FullPath = Join-Path $RepoRoot $Path
    if (-not (Test-Path $FullPath)) {
        throw "missing file for $Label`: $Path"
    }
    if (-not (Select-String -LiteralPath $FullPath -Pattern $Pattern -Quiet)) {
        throw "missing Phase R static marker [$Label] in $Path`: $Pattern"
    }
}

function Assert-NotContains {
    param(
        [string]$Path,
        [string]$Pattern,
        [string]$Label
    )
    $FullPath = Join-Path $RepoRoot $Path
    if (-not (Test-Path $FullPath)) {
        throw "missing file for $Label`: $Path"
    }
    if (Select-String -LiteralPath $FullPath -Pattern $Pattern -Quiet) {
        throw "forbidden Phase R static marker [$Label] in $Path`: $Pattern"
    }
}

Assert-Contains "tools\benchmarks\run_phase_r_integrator_smoke.ps1" "samples_per_second" "R.0 benchmark smoke metric"
Assert-Contains "libs\ure_core\src\path_tracer_host_api.cu" "launch_blocks_for_active_count" "R.1 active-count launch"
Assert-Contains "libs\ure_core\src\path_tracer_host_api.cu" "current_ray_count <= 0" "R.1 empty-queue termination"
Assert-Contains "libs\ure_core\include\ure\gpu_context.hpp" "last_integrator_ray_queue_overflow_count" "R.2 ray overflow telemetry"
Assert-Contains "libs\ure_core\include\ure\gpu_structs.hpp" "overflow_count" "R.2 queue overflow counter"
Assert-Contains "libs\ure_core\include\ure\path_tracer_sampling.cuh" "sample_path_dimension" "R.3 unified path dimensions"
Assert-Contains "libs\ure_core\src\path_tracer_wavefront.cuh" "kPathDimVolumePhaseU" "R.3 volume phase dimensions"
Assert-Contains "libs\ure_core\src\path_tracer_host_api.cu" "build_light_alias_table" "R.4 weighted light alias table"
Assert-Contains "libs\ure_core\src\path_tracer_wavefront.cuh" "sample_light_list_index" "R.4 unified light selection"
Assert-Contains "libs\ure_core\include\ure\gpu_spectrum_utils.cuh" "scene_cie_mixture_wavelength_pdf" "R.5 scene/CIE wavelength mixture PDF"
Assert-Contains "libs\ure_core\src\path_tracer_raygen.cu" "sample_scene_cie_mixture_wavelength" "R.5 proposal-driven raygen"
Assert-Contains "tests\gpu\test_spectral_pipeline.cu" "test_narrowband_scene_proposal_reduces_spd_estimator_error" "R.5 narrowband proposal oracle"
Assert-Contains "libs\ure_core\src\path_tracer_volume.cuh" "Mie = 2" "R.6 Mie enum boundary"
Assert-Contains "libs\ure_core\src\path_tracer_volume.cuh" "is_supported_analytic_volume_phase_function" "R.6 analytic phase support gate"
Assert-Contains "tests\gpu\test_gpu_volume.cu" "test_volume_phase_selector_boundary" "R.6 volume phase selector test"
Assert-Contains "tests\gpu\test_spectral_pipeline_soa.cu" "rough_dielectric_energy_bound" "R.6 rough dielectric energy oracle"
Assert-Contains "tests\gpu\test_gpu_polarization.cu" "test_thin_film_sp_energy_grid" "R.6 thin-film energy oracle"
Assert-Contains "libs\ure_types\include\ure\render_config.hpp" "PathGuidingConfig" "R.7 path guiding config"
Assert-Contains "libs\ure_core\src\path_tracer_wavefront.cuh" "guided_mixture_light_selection_pdf" "R.7 guided light PDF"
Assert-Contains "libs\ure_core\src\path_tracer_wavefront.cuh" "path_guiding_light_weights" "R.7 guide cache device path"
Assert-Contains "libs\ure_config\src\config_impl.cpp" "path-guiding-min-weight" "R.7 path guiding min-weight CLI parity"
Assert-Contains "libs\ure_core\src\path_tracer_host_api.cu" "validate_path_guiding_config" "R.7 path guiding fail-loud validation"
Assert-Contains "tests\gpu\test_render_basic.cu" "test_path_guiding_shadow_visibility_updates_light_weight" "R.7 progressive guide update test"
Assert-Contains "tests\gpu\test_render_basic.cu" "test_path_guiding_rejects_invalid_enabled_config" "R.7 invalid path guiding config test"
Assert-Contains "tests\host\test_config.cpp" "test_path_guiding_cli_overrides" "R.7 config parity test"
Assert-Contains "libs\ure_types\include\ure\render_config.hpp" "RestirDirectConfig" "R.8 ReSTIR DI config"
Assert-Contains "libs\ure_core\src\path_tracer_wavefront.cuh" "enqueue_restir_di_temporal_replay" "R.8 temporal ReSTIR DI replay path"
Assert-Contains "libs\ure_core\src\path_tracer_wavefront.cuh" "store_restir_di_visible_candidate" "R.8 visible candidate reservoir update"
Assert-Contains "libs\ure_core\include\ure\gpu_structs.hpp" "restir_di_stokes_i" "R.8 Stokes-compatible reservoir metadata"
Assert-Contains "libs\ure_core\include\ure\integrator\restir_di.cuh" "merge_restir_di_reservoir" "R-P3 generalized reservoir merge contract"
Assert-Contains "libs\ure_core\include\ure\integrator\restir_di.cuh" "restir_defensive_pairwise_weights" "R-P3 defensive pairwise MIS contract"
Assert-Contains "libs\ure_core\include\ure\integrator\restir_di.cuh" "finalize_restir_di_gris_reservoir" "R-P3 reciprocal marginal contribution weight"
Assert-Contains "libs\ure_core\include\ure\gpu_structs.hpp" "GpuRestirDIReservoir" "R-P3 production reservoir storage"
Assert-Contains "libs\ure_core\include\ure\gpu_structs.hpp" "source_geometric_normal" "R-P3 bidirectional reconnection metadata"
Assert-Contains "libs\ure_types\include\ure\render_config.hpp" "normal_threshold" "R-P3 reconnection threshold config"
Assert-Contains "libs\ure_types\include\ure\render_config.hpp" "RestirPT" "R-P3 independent ReSTIR PT mode"
Assert-Contains "libs\ure_core\src\restir_pt_runtime.cu" "prepare_restir_pt_candidate_kernel" "R-P3 separate ReSTIR PT replay pass"
Assert-Contains "libs\ure_core\src\restir_pt_runtime.cu" "finalize_restir_pt_reservoir_kernel" "R-P3 PT reservoir normalization pass"
Assert-Contains "libs\ure_core\src\restir_pt_capture.cuh" "capture_restir_pt_surface_vertex" "R-P3 actual surface suffix capture"
Assert-Contains "libs\ure_core\src\restir_pt_capture.cuh" "capture_restir_pt_volume_vertex" "R-P3 actual volume suffix capture"
Assert-Contains "libs\ure_core\include\ure\integrator\restir_pt.cuh" "forward_pdf" "R-P3 path forward PDF metadata"
Assert-Contains "libs\ure_core\include\ure\integrator\restir_pt.cuh" "reverse_pdf" "R-P3 path reverse PDF metadata"
Assert-Contains "libs\ure_core\include\ure\gpu_structs.hpp" "sample_indices" "R-P3 per-ray replay sample identity"
Assert-Contains "tests\gpu\test_render_basic.cu" "test_restir_pt_replays_diffuse_surface_suffixes" "R-P3 surface path reuse E2E"
Assert-Contains "tests\gpu\test_render_basic.cu" "test_restir_pt_replays_scalar_depolarizing_volume_suffixes" "R-P3 volume path reuse E2E"
Assert-Contains "tests\gpu\test_render_basic.cu" "test_restir_pt_rejects_specular_suffix_without_manifold_shift" "R-P3 specular fail-loud boundary"
Assert-Contains "tools\benchmarks\run_phase_r_restir_pt_suite.ps1" "restir_pt_bias_variance_time_to_error" "R-P3 bias and benefit curves"
Assert-Contains "tools\benchmarks\run_phase_r_restir_pt_suite.ps1" "relative_bias_95_bound" "R-P3 statistical bias bound"
Assert-Contains "tools\benchmarks\run_phase_r_restir_pt_suite.ps1" "reservoir_telemetry" "R-P3 reservoir rejection counters"
Assert-NotContains "libs\ure_core\src\path_tracer_host_api.cu" "ReSTIR PT is not implemented yet" "R-P3 obsolete PT fail-loud"
Assert-Contains "libs\ure_core\include\ure\specular_manifold.hpp" "BidirectionalPdfVertex" "R-P4 shared path-space PDF contract"
Assert-Contains "libs\ure_core\src\specular_manifold.cpp" "bidirectional_power_heuristic" "R-P4 technique MIS oracle"
Assert-Contains "libs\ure_core\src\specular_manifold.cpp" "reconstruct_bidirectional_strategy_probabilities" "R-P4 same-path strategy density reconstruction"
Assert-Contains "libs\ure_core\src\specular_manifold.cpp" "progressive_volume_merge_radius" "R-P4 dimensional VCM radius schedule"
Assert-Contains "libs\ure_types\include\ure\render_config.hpp" "BDPT" "R-P4 BDPT runtime mode"
Assert-Contains "libs\ure_types\include\ure\render_config.hpp" "VCM" "R-P4 VCM runtime mode"
Assert-Contains "libs\ure_core\include\ure\integrator\bidirectional.cuh" "GpuBidirectionalPathVertex" "R-P4 shared GPU path vertex ABI"
Assert-Contains "libs\ure_core\src\bidirectional_runtime.cu" "generate_light_subpath_endpoints_kernel" "R-P4 typed light endpoint generation"
Assert-Contains "libs\ure_core\src\bidirectional_runtime.cu" "connect_bidirectional_subpaths_kernel" "R-P4 visible camera-light connection"
Assert-Contains "libs\ure_core\src\bidirectional_runtime.cu" "extend_light_subpaths_kernel" "R-P4 recursive light subpath generation"
Assert-Contains "libs\ure_core\src\path_tracer_material.cu" "BoundaryTransportMode transport_mode" "R-P4 explicit radiance/importance boundary transport"
Assert-Contains "libs\ure_core\src\bidirectional_runtime.cu" "build_bidirectional_complete_path_edges" "R-P4 complete connection path density"
Assert-Contains "libs\ure_core\include\ure\integrator\bidirectional.cuh" "bidirectional_connection_vcm_mis_weight" "R-P4 connection and merge shared MIS denominator"
Assert-Contains "libs\ure_core\src\bidirectional_runtime.cu" "bidirectional_complete_path_connection_mis_weight" "R-P4 full connection strategy MIS consumption"
Assert-Contains "libs\ure_core\src\bidirectional_runtime.cu" "vcm_complete_path_merge_mis_weight" "R-P4 full merge strategy MIS consumption"
Assert-Contains "libs\ure_core\src\bidirectional_runtime.cu" "albedo_expression_root" "R-P4 current MaterialGraph target reevaluation"
Assert-Contains "libs\ure_core\src\bidirectional_capture.cuh" "capture_bidirectional_surface_vertex" "R-P4 actual camera path capture"
Assert-Contains "libs\ure_core\include\ure\gpu_structs.hpp" "path_indices" "R-P4 stable per-ray path identity"
Assert-Contains "tests\gpu\test_render_basic.cu" "nonzero_connection" "R-P4 GPU ownership and connection E2E"
Assert-Contains "tests\gpu\test_render_basic.cu" "light_vertices > 16" "R-P4 multi-vertex light subpath E2E"
Assert-Contains "tests\gpu\test_render_basic.cu" "test_bidirectional_strategy_density_partitions_on_device" "R-P4 device strategy partition oracle"
Assert-Contains "tests\host\test_config.cpp" "test_bidirectional_and_vcm_cli_overrides" "R-P4 CLI config parity"
Assert-Contains "tests\gpu\test_render_basic.cu" "test_restir_di_reconstructs_light_at_current_reference_point" "R-P3 current-reference light reconstruction"
Assert-Contains "tests\gpu\test_render_basic.cu" "test_restir_di_visible_shadow_updates_reservoir_metadata" "R.8 reservoir metadata test"
Assert-Contains "tests\host\test_config.cpp" "test_restir_di_cli_overrides" "R.8 config parity test"
Assert-Contains "libs\ure_types\include\ure\render_config.hpp" "SpecularManifoldConfig" "R.9 specular manifold config"
Assert-Contains "libs\ure_core\include\ure\specular_manifold.hpp" "SpecularInterfaceConnection" "R.9 specular interface oracle contract"
Assert-Contains "libs\ure_core\src\specular_manifold.cpp" "forward_solid_angle_jacobian" "R.9 Jacobian oracle"
Assert-Contains "libs\ure_core\src\bidirectional_runtime.cu" "solve_specular_manifold_paths_kernel" "R-P4 production manifold solve pass"
Assert-Contains "libs\ure_core\include\ure\gpu_context.hpp" "d_manifold_solutions" "R-P4 owned manifold solution artifacts"
Assert-Contains "libs\ure_core\include\ure\integrator\specular_manifold.cuh" "Occluded" "R-P4 typed manifold visibility rejection"
Assert-Contains "tests\gpu\test_render_basic.cu" "rejected_occluded" "R-P4 manifold blocker E2E"
Assert-Contains "libs\ure_core\include\ure\integrator\specular_manifold.cuh" "evaluate_gpu_manifold_differential" "R-P4 generalized geometry differential"
Assert-Contains "libs\ure_core\include\ure\integrator\specular_manifold.cuh" "endpoint_area_jacobian" "R-P4 parameterization-invariant area map"
Assert-Contains "tests\gpu\test_render_basic.cu" "0.08838835f" "R-P4 analytic planar mirror geometry oracle"
Assert-Contains "libs\ure_core\src\path_tracer_host_api.cu" "standalone_manifold" "R-P4 standalone estimator scheduling"
Assert-Contains "libs\ure_core\src\path_tracer_host_api.cu" "while \(pending_count > 0\)" "R-P4 reciprocal-root drain"
Assert-Contains "libs\ure_core\src\path_tracer_wavefront.cuh" "manifold_sms_partition" "R-P4 wavefront support partition"
Assert-Contains "libs\ure_core\src\path_tracer_wavefront.cuh" "\(flag & 3\) == 3" "R-P4 anchored-delta support identity"
Assert-Contains "libs\ure_core\include\ure\gpu_context.hpp" "d_specular_emitter_accum" "R-P4 independent technique AOV"
Assert-Contains "tools\benchmarks\run_phase_r_manifold_suite.ps1" "specular_emitter" "R-P4 independent wavefront reference"
Assert-Contains "tools\benchmarks\run_phase_r_manifold_suite.ps1" "relative_bias_95_bound" "R-P4 statistical bias bound"
Assert-NotContains "libs\ure_core\src\path_tracer_host_api.cu" "BDPT/VCM camera-light connection is under R-P4 implementation" "R-P4 obsolete estimator fail-loud"
Assert-Contains "tests\host\test_integrator.cpp" "test_specular_interface_oblique_jacobian_reciprocity" "R.9 Jacobian reciprocity test"
Assert-Contains "libs\ure_types\include\ure\render_config.hpp" "MltIntegratorConfig" "R.10 MLT config"
Assert-Contains "libs\ure_core\include\ure\specular_manifold.hpp" "PrimarySampleMutation" "R.10 primary sample mutation oracle contract"
Assert-Contains "libs\ure_core\src\specular_manifold.cpp" "metropolis_acceptance" "R.10 Metropolis acceptance oracle"
Assert-NotContains "libs\ure_core\src\path_tracer_host_api.cu" "MLT primary-sample-space GPU integrator is not implemented yet" "R-P5 obsolete MLT fail-loud"
Assert-Contains "libs\ure_core\src\path_tracer_host_api.cu" "render_mlt_pass" "R-P5 independent chain scheduler"
Assert-Contains "libs\ure_core\src\mlt_runtime.cu" "accept_and_deposit_mlt_kernel" "R-P5 Metropolis deposition runtime"
Assert-Contains "libs\ure_core\src\mlt_runtime.cu" "const float sign = u2 < 0.5f" "R-P5 wrapped symmetric Laplace small step"
Assert-Contains "libs\ure_core\src\mlt_runtime.cu" "const float jitter = mlt_uniform" "R-P5 per-shard stratified bootstrap seeding"
Assert-Contains "libs\ure_core\src\path_tracer_host_api.cu" "mlt_primary_dimension_count = dimensions" "R-P5 bounded primary dimension storage"
Assert-Contains "libs\ure_core\src\bidirectional_capture.cuh" "capture_bidirectional_emitter_vertex" "R-P5 camera-only MIS technique"
Assert-Contains "libs\ure_core\src\path_tracer_host_api.cu" "sensor-measure estimator" "R-P5 unsupported pinhole light-tracing gate"
Assert-Contains "libs\ure_core\src\path_tracer_host_api.cu" "share one spectral primary-sample contract" "R-P5 MLT bidirectional spectral boundary"
Assert-Contains "libs\ure_core\include\ure\path_tracer_sampling.cuh" "queue.primary_samples" "R-P5 shared primary-sample replay boundary"
Assert-Contains "libs\ure_core\src\gpu_multi_driver.cu" "make_mlt_chain_shard" "R-P5 multi-GPU chain identity partition"
Assert-Contains "tools\benchmarks\run_phase_r_mlt_suite.ps1" "time_to_error_benefit" "R-P5 difficult-scene time-to-error gate"
Assert-Contains "tools\benchmarks\run_phase_r_mlt_suite.ps1" "TargetNormalizedMse" "R-P5 fixed normalized-error target"
Assert-Contains "tools\benchmarks\run_phase_r_mlt_suite.ps1" "normalized_mse" "R-P5 scale-independent error metric"
Assert-Contains "tests\gpu\test_render_basic.cu" "test_mlt_runtime_replays_and_reports_chain_diagnostics" "R-P5 deterministic GPU chain E2E"
Assert-Contains "tests\host\test_integrator.cpp" "test_mlt_primary_sample_mutation_replays_deterministically" "R.10 deterministic replay test"
Assert-Contains "tests\host\test_config.cpp" "test_integrator_mlt_cli_overrides" "R.10 config parity test"
Assert-Contains "libs\ure_types\include\ure\render_config.hpp" "IntegratorRuntimeConfig" "R.11 unified integrator runtime config"
Assert-Contains "libs\ure_core\include\ure\ure_c_api.h" "ure_integrator_config_t" "R.11 C ABI integrator config"
Assert-Contains "pyure\__init__.py" "integrator_mode" "R.11 pyure integrator mode"
Assert-Contains "libs\ure_core\src\path_tracer_host_api.cu" "validate_integrator_runtime_config" "R.11 unsupported integrator combination gate"
Assert-Contains "tests\host\test_config.cpp" "test_integrator_runtime_cli_overrides" "R.11 config parity test"
Assert-Contains "tests\host\test_integrator.cpp" "test_integrator_rejects_restir_mode_without_biased_ack" "R.11 unsupported combination test"
Assert-Contains "tests\host\test_session.cpp" "ure_session_create_integrator_config" "R.11 C ABI session test"
Assert-Contains "tools\benchmarks\run_phase_r_validation_suite.ps1" "ure.phase_r.industrial_validation.v1" "R-P7 versioned industrial report contract"
Assert-Contains "tools\benchmarks\validate_phase_r_industrial_report.ps1" "Closure" "R-P7 closure profile gate"
Assert-Contains "tools\benchmarks\validate_phase_r_industrial_report.ps1" "farm sample ranges contain a gap or overlap" "R-P7 exact farm coverage gate"
Assert-Contains "tools\benchmarks\validate_phase_r_industrial_report.ps1" "occupancy_pct" "R-P7 measured occupancy gate"
Assert-Contains "tools\benchmarks\collect_phase_r_vram_evidence.ps1" "device_used_delta" "R-P7 measured VRAM delta evidence"
Assert-Contains "tools\benchmarks\convert_phase_r_nsight_csv.ps1" "sm__warps_active.avg.pct_of_peak_sustained_active" "R-P7 achieved occupancy import"
Assert-Contains "tools\benchmarks\run_phase_r_manifold_suite.ps1" "camera_delta_outside_anchored_sms_support" "R-P7 manifold support boundary scene"
Assert-Contains "tools\benchmarks\run_phase_r_bidirectional_suite.ps1" "ure.phase_r.bidirectional_suite.v1" "R-P7 versioned BDPT/VCM evidence"
Assert-Contains "tools\benchmarks\run_phase_r_bidirectional_suite.ps1" "camera_delta_outside_ordinary_connection_and_photon_merge_support" "R-P7 BDPT/VCM support boundary scene"
Assert-Contains "tools\benchmarks\run_phase_r_path_guiding_suite.ps1" "path_guided requires path_guiding.enabled" "R-P7 path-guiding fail-loud boundary scene"
Assert-Contains "tools\benchmarks\run_phase_r_restir_pt_suite.ps1" "restir_pt requires restir_pt.enabled" "R-P7 ReSTIR PT fail-loud boundary scene"
Assert-Contains "tools\benchmarks\run_phase_r_mlt_suite.ps1" "cannot be combined with adaptive reuse" "R-P7 MLT scheduler-ownership boundary scene"
Assert-Contains "tests\gpu\phase_r_guiding_benchmark.cu" "vcm_surface_merge" "R-P7 independent VCM technique AOV"
Assert-Contains "tests\gpu\phase_r_guiding_benchmark.cu" "bidirectional_connection" "R-P7 independent BDPT technique AOV"
Assert-Contains "tools\benchmarks\run_phase_r_validation_suite.ps1" "phase_r_ctest_evidence" "R-P7 hashed correctness evidence"
Assert-Contains "tools\benchmarks\run_phase_r_validation_suite.ps1" "phase_r_integrator_smoke.json" "R.12 benchmark report ingestion"
Assert-Contains "tools\benchmarks\run_phase_r_light_sampling_suite.ps1" "light_sampling_variance_mse_local" "R-P1 multi-scene light sampling variance/MSE suite"
Assert-Contains "tools\benchmarks\run_phase_r_validation_suite.ps1" "light_sampling" "R-P1 validation suite light sampling gate"
Assert-Contains "scenes\benchmarks\phase_r_multi_light_sampling.gltf" "phase_r_emissive_quad" "R-P1 multi-light benchmark scene"
Assert-Contains "libs\ure_core\src\session.cpp" "requires_scene_reload_for_material_update" "R-P1 resource material mutation full-reload boundary"
Assert-Contains "tests\host\test_session.cpp" "test_scene_diff_material_graph_update_ir_full_reload" "R-P1 MaterialGraph mutation reload test"
Assert-Contains "tests\host\test_session.cpp" "test_scene_diff_material_spd_update_ir_full_reload" "R-P1 spectral resource mutation reload test"
Assert-Contains "libs\ure_types\include\ure\render_config.hpp" "spatial_cell_count" "R-P2 spatial guide config"
Assert-Contains "libs\ure_types\include\ure\render_config.hpp" "directional_bin_count" "R-P2 directional guide config"
Assert-Contains "libs\ure_core\include\ure\gpu_context.hpp" "d_path_guiding_spatial_directional_weights" "R-P2 GPU resident spatial-directional cache"
Assert-Contains "libs\ure_core\src\path_tracer_light_sampling.cuh" "path_guiding_spatial_directional_light_weight" "R-P2 spatial-directional proposal weight"
Assert-Contains "libs\ure_core\src\path_tracer_wavefront.cuh" "guided_mixture_light_selection_pdf_at" "R-P2 reference-conditioned guide PDF"
Assert-Contains "tests\gpu\test_render_basic.cu" "test_path_guiding_spatial_directional_selection_uses_matching_pdf" "R-P2 proposal/PDF parity test"
Assert-Contains "tests\host\test_session.cpp" "test_scene_diff_emissive_instance_transform_ir_full_reload" "R-P2 emissive transform reload test"
Assert-Contains "tests\gpu\test_render_basic.cu" "test_emissive_instance_transform_hot_update_requires_full_reload" "R-P2 raw GPU emissive transform fail-loud"
Assert-Contains "tests\gpu\test_instance_hotupdate.cu" "test_gpu_hot_update_resets_spatial_guiding_epoch" "R-P2 transform guide epoch reset"
Assert-Contains "libs\ure_core\src\path_tracer_wavefront.cuh" "path_guiding_product_metadata" "R-P2 spectral product target metadata"
Assert-Contains "libs\ure_core\src\path_tracer_wavefront.cuh" "decay_path_guiding_weights_kernel" "R-P2 guide decay kernel"
Assert-Contains "libs\ure_core\src\path_tracer_wavefront.cuh" "guiding_epochs.*path_guiding_epoch" "R-P2 stale epoch rejection"
Assert-Contains "tests\gpu\test_render_basic.cu" "test_path_guiding_product_target_uses_wavelength_pdf_metadata" "R-P2 product target spectral metadata test"
Assert-Contains "tests\gpu\test_render_basic.cu" "test_path_guiding_decay_kernel_applies_epoch_factor" "R-P2 decay test"
Assert-Contains "libs\ure_core\src\gpu_multi_driver.cu" "merge_path_guiding_delta_kernel" "R-P2 multi-GPU guide delta merge"
Assert-Contains "libs\ure_core\src\gpu_multi_driver.cu" "d_path_guiding_baseline_light" "R-P2 multi-GPU shared guide baseline"
Assert-Contains "libs\ure_core\src\path_tracer_host_api.cu" "plan_path_guiding_memory" "R-P2 guide memory planner"
Assert-Contains "libs\ure_config\src\config_impl.cpp" "path-guiding-memory-budget-mb" "R-P2 guide memory budget config parity"
Assert-Contains "tests\gpu\test_render_basic.cu" "test_multi_gpu_path_guiding_merge_preserves_single_history" "R-P2 multi-GPU merge formula test"
Assert-Contains "tools\benchmarks\run_phase_r_path_guiding_suite.ps1" "path_guiding_variance_mse_time_to_error" "R-P2 four-scene benefit curves"
Assert-Contains "tests\gpu\phase_r_guiding_benchmark.cu" "complex_material" "R-P2 complex material benchmark workload"
Assert-Contains "tests\gpu\phase_r_guiding_benchmark.cu" "update_medium_gpu" "R-P2 participating medium benchmark workload"
Assert-Contains "libs\ure_core\include\ure\gpu_structs.hpp" "GpuMiePhaseResource" "R-P6 GPU Mie descriptor"
Assert-Contains "libs\ure_core\src\mie_solver.cpp" "generate_mie_phase_resource" "R-P6 Lorenz-Mie generator"
Assert-Contains "libs\ure_sceneio\src\mie_phase_io.cpp" "load_mie_phase_table" "R-P6 imported table adapter"
Assert-Contains "libs\ure_types\include\ure\mie_phase_validation.hpp" "validate_mie_phase_resource" "R-P6 shared validation boundary"
Assert-Contains "libs\ure_core\src\gpu_scene_compiler.cpp" "Mie medium requires a phase resource" "R-P6 missing-resource fail-loud"
Assert-Contains "libs\ure_core\src\path_tracer_wavefront.cuh" "load_mie_medium_cross_sections" "R-P6 spectral cross sections"
Assert-Contains "libs\ure_core\src\path_tracer_wavefront.cuh" "sample_mie_packet_phase_lds_pdf" "R-P6 continuation proposal"
Assert-Contains "libs\ure_core\src\path_tracer_wavefront.cuh" "apply_volume_phase_polarization" "R-P6 depolarizing Stokes contract"
Assert-Contains "tests\gpu\test_gpu_volume.cu" "test_mie_scene_ir_generated_and_imported_lifecycle" "R-P6 end-to-end lifecycle"
Assert-Contains "tests\host\test_session.cpp" "test_scene_diff_changed_mie_resource_forces_full_reload" "R-P6 retained-scene rebuild"
Assert-NotContains "libs\ure_core\src\path_tracer_wavefront.cuh" "sample_volume_phase_lds_pdf\s*\(\s*VolumePhaseFunction::HenyeyGreenstein" "R-P6 hard-coded HG production dispatch"

Write-Host "Phase R static audit passed"
