set(PACKAGE_VERSION "0.3.0")

if(PACKAGE_FIND_VERSION STREQUAL PACKAGE_VERSION)
    set(PACKAGE_VERSION_EXACT TRUE)
    set(PACKAGE_VERSION_COMPATIBLE TRUE)
else()
    set(PACKAGE_VERSION_COMPATIBLE FALSE)
endif()

if(NOT CMAKE_SIZEOF_VOID_P EQUAL 8 OR NOT WIN32)
    set(PACKAGE_VERSION_UNSUITABLE TRUE)
endif()
